name: Hello to You Docker
description: Prints a greeting message in a Docker container
inputs:
    name:
        description: Your name
        required: true
        default: World
runs:
    using: docker
    image: Dockerfile